/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'bg-main': 'var(--color-bg-main)',
        'bg-surface': 'var(--color-bg-surface)',
        'bg-dark': 'var(--color-bg-dark)',

        'primary': 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-soft': 'var(--color-primary-soft)',

        'accent': 'var(--color-accent)',
        'accent-soft': 'var(--color-accent-soft)',

        'main': 'var(--color-text-primary)',
        'text-primary': 'var(--color-text-primary)',
        'secondary': 'var(--color-text-secondary)',
        'text-secondary': 'var(--color-text-secondary)',
        'muted': 'var(--color-text-muted)',
        'text-muted': 'var(--color-text-muted)',
        'inverse': 'var(--color-text-inverse)',
        'text-inverse': 'var(--color-text-inverse)',

        'border': 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        'border-dark': 'var(--color-border-dark)',

        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error': 'var(--color-error)',
      },
      fontSize: {
        'display-xl': 'var(--text-display-xl)',
        'display-lg': 'var(--text-display-lg)',
        'h1': 'var(--text-h1)',
        'h2': 'var(--text-h2)',
        'h3': 'var(--text-h3)',
        'h4': 'var(--text-h4)',
        'body-lg': 'var(--text-body-lg)',
        'body': 'var(--text-body)',
        'sm': 'var(--text-sm)',
        'xs': 'var(--text-xs)',
      },
      fontFamily: {
        'display': 'var(--font-display)',
        'body': 'var(--font-body)',
      },
      lineHeight: {
        'tight': 'var(--leading-tight)',
        'heading': 'var(--leading-heading)',
        'body': 'var(--leading-body)',
      },
      fontWeight: {
        'regular': 'var(--weight-regular)',
        'medium': 'var(--weight-medium)',
        'semibold': 'var(--weight-semibold)',
        'bold': 'var(--weight-bold)',
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        '30': 'var(--space-30)',
        '40': 'var(--space-40)',
        'gutter-mobile': 'var(--page-gutter-mobile)',
        'gutter-tablet': 'var(--page-gutter-tablet)',
        'gutter-laptop': 'var(--page-gutter-laptop)',
        'gutter-desktop': 'var(--page-gutter-desktop)',
      },
      maxWidth: {
        'container': 'var(--container-max)',
      },
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'pill': 'var(--radius-pill)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
      },
      transitionDuration: {
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'medium': 'var(--duration-medium)',
        'slow': 'var(--duration-slow)',
        'page': 'var(--duration-page)',
      },
      transitionTimingFunction: {
        'standard': 'var(--ease-standard)',
        'out': 'var(--ease-out)',
        'emphasized': 'var(--ease-emphasized)',
      },
      zIndex: {
        'base': 'var(--z-base)',
        'decorative': 'var(--z-decorative)',
        'content': 'var(--z-content)',
        'sticky': 'var(--z-sticky)',
        'header': 'var(--z-header)',
        'dropdown': 'var(--z-dropdown)',
        'modal': 'var(--z-modal)',
        'toast': 'var(--z-toast)',
      },
    },
  },
  plugins: [],
}
